apiVersion: v1
kind: Service
metadata:
  name: chuck-norris-app
  namespace: dev
spec:
  ports:
  - nodePort: 31808
    port: 8080
    protocol: TCP
  selector:
    app: chuck-norris-app
  type: NodePort
